# Generated by Django 5.2.7 on 2026-03-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesession',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
